# Generated by Django 4.2.14 on 2025-11-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='assistance_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='assistance_suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='assistance_suspension_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
