# Generated by Django 5.2.7 on 2025-12-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_organization_org_type_alter_orgmembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('SCHOOL', 'School'), ('NGO', 'NGO'), ('SAPA', 'SAPA'), ('INDITECH', 'Inditech'), ('MANUFACTURER', 'Manufacturer'), ('LOGISTICS', 'Logistics Partner')], default='SCHOOL', max_length=16),
        ),
        migrations.AlterField(
            model_name='orgmembership',
            name='role',
            field=models.CharField(choices=[('ORG_ADMIN', 'School Admin'), ('TEACHER', 'Teacher'), ('SAPA_ADMIN', 'SAPA Admin'), ('INDITECH', 'Inditech'), ('SAPA_PGC', 'SAPA Governing Committee'), ('MANUFACTURER', 'Manufacturer'), ('LOGISTICS', 'Logistics Partner')], max_length=16),
        ),
    ]
