# Generated by Django 5.2.7 on 2025-12-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productionorder',
            new_name='fulfillment_status_ea3cc7_idx',
            old_name='fulfillment__status_f8c2bb_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolshipment',
            new_name='fulfillment_school__f8eb02_idx',
            old_name='fulfillment__school_7c4fcf_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolshipment',
            new_name='fulfillment_status_af2822_idx',
            old_name='fulfillment__status_9e05be_idx',
        ),
        migrations.RenameIndex(
            model_name='shipmentitem',
            new_name='fulfillment_shipmen_92393a_idx',
            old_name='fulfillment__shipment_0d1b40_idx',
        ),
    ]
