# Generated by Django 4.2.14 on 2025-11-18 08:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_index', models.PositiveSmallIntegerField()),
                ('scheduled_delivery_date', models.DateField(blank=True, null=True)),
                ('delivered_on', models.DateField(blank=True, null=True)),
                ('compliance_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('qr_token', models.CharField(max_length=96, unique=True)),
                ('ok_to_ship_next', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='program.enrollment')),
            ],
            options={
                'indexes': [models.Index(fields=['delivered_on'], name='program_mon_deliver_131b5f_idx'), models.Index(fields=['compliance_due_at'], name='program_mon_complia_0835b6_idx')],
                'unique_together': {('enrollment', 'month_index')},
            },
        ),
    ]
