# Generated by Django 4.2.14 on 2025-11-18 19:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_monthlysupply'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_SUBMITTED', 'Not submitted'), ('COMPLIANT', 'Submitted & compliant'), ('UNABLE', 'Submitted & unable')], default='NOT_SUBMITTED', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('responses', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthly_supply', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance', to='program.monthlysupply')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='program_com_status_245219_idx')],
            },
        ),
    ]
