# Generated by Django 4.2.14 on 2025-11-20 05:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
        ('program', '0003_compliancesubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(choices=[('MONTH_3', '3-month'), ('MONTH_6', '6-month')], max_length=16)),
                ('due_on', models.DateField()),
                ('status', models.CharField(choices=[('DUE', 'Due'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='DUE', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_screening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='screening.screening')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='program.enrollment')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'due_on'], name='program_scr_status_72099d_idx'), models.Index(fields=['enrollment', 'milestone'], name='program_scr_enrollm_980cd2_idx')],
                'unique_together': {('enrollment', 'milestone')},
            },
        ),
    ]
