# Generated by Django 5.2.7 on 2026-02-07 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_organization_org_type_alter_orgmembership_role'),
        ('roster', '0002_alter_guardian_unique_together_and_more'),
        ('screening', '0002_yellow_and_anthro_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='screening',
            name='screening_s_student_3d255f_idx',
        ),
        migrations.RemoveIndex(
            model_name='screening',
            name='screening_s_organiz_de7d88_idx',
        ),
        migrations.AddField(
            model_name='screening',
            name='pid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='screening',
            index=models.Index(fields=['organization', 'screened_at'], name='screening_s_organiz_ce9197_idx'),
        ),
        migrations.AddIndex(
            model_name='screening',
            index=models.Index(fields=['organization', 'student', 'screened_at'], name='screening_s_organiz_968f92_idx'),
        ),
        migrations.AddIndex(
            model_name='screening',
            index=models.Index(fields=['organization', 'risk_level', 'screened_at'], name='screening_s_organiz_218374_idx'),
        ),
        migrations.AddIndex(
            model_name='screening',
            index=models.Index(fields=['organization', 'pid', 'screened_at'], name='screening_s_organiz_526dda_idx'),
        ),
    ]
