# Generated by Django 5.2.7 on 2025-12-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='grant',
            new_name='grants_gran_status_6b1bfa_idx',
            old_name='grants_gran_status_6df4d7_idx',
        ),
        migrations.RenameIndex(
            model_name='grantallocation',
            new_name='grants_gran_allocat_073927_idx',
            old_name='grants_gran_allocat_0fe7b7_idx',
        ),
        migrations.RenameIndex(
            model_name='grantallocation',
            new_name='grants_gran_grant_i_fb7715_idx',
            old_name='grants_gran_grant_i_4f9db2_idx',
        ),
    ]
