# Generated by Django 4.2.14 on 2025-11-12 16:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(max_length=64)),
                ('division', models.CharField(blank=True, max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_e164', models.CharField(max_length=20)),
                ('whatsapp_opt_in', models.BooleanField(default=True)),
                ('preferred_language', models.CharField(default='en', max_length=8)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('dob', models.DateField(blank=True, null=True)),
                ('student_code', models.CharField(blank=True, max_length=64)),
                ('is_low_income', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='roster.classroom')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.organization')),
                ('primary_guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='roster.guardian')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('MOTHER', 'Mother'), ('FATHER', 'Father'), ('GUARDIAN', 'Guardian')], default='GUARDIAN', max_length=16)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='roster.guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='roster.student')),
            ],
            options={
                'unique_together': {('student', 'guardian')},
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['organization', 'last_name', 'first_name'], name='roster_stud_organiz_7422ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('organization', 'student_code')},
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['organization', 'full_name'], name='roster_guar_organiz_cb5098_idx'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['organization', 'phone_e164'], name='roster_guar_organiz_62ee3f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guardian',
            unique_together={('organization', 'phone_e164')},
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['organization', 'grade', 'division'], name='roster_clas_organiz_470a98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('organization', 'grade', 'division')},
        ),
    ]
