# Generated by Django 5.2.7 on 2026-02-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_organization_org_type_alter_orgmembership_role'),
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guardian',
            unique_together={('organization', 'phone_e164')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('organization', 'student_code')},
        ),
        migrations.AddField(
            model_name='guardian',
            name='pid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='full_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='phone_e164',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='guardian',
            unique_together={('organization', 'phone_e164'), ('organization', 'pid')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('organization', 'pid'), ('organization', 'student_code')},
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['organization', 'pid'], name='roster_guar_organiz_930881_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['organization', 'pid'], name='roster_stud_organiz_f2386c_idx'),
        ),
    ]
