# Generated by Django 5.2.7 on 2026-02-14 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_organization_org_type_alter_orgmembership_role'),
        ('roster', '0002_alter_guardian_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('organization', 'classroom', 'student_code'), ('organization', 'pid')},
        ),
    ]
