# Generated by Django 4.2.14 on 2025-11-20 13:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_organization_assistance_suspended_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolReportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_period_start', models.DateField(blank=True, null=True)),
                ('last_period_end', models.DateField(blank=True, null=True)),
                ('next_due_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_status', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolStatDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('screened', models.PositiveIntegerField(default=0)),
                ('red_flags', models.PositiveIntegerField(default=0)),
                ('applied', models.PositiveIntegerField(default=0)),
                ('forwarded', models.PositiveIntegerField(default=0)),
                ('approved', models.PositiveIntegerField(default=0)),
                ('rejected', models.PositiveIntegerField(default=0)),
                ('enrollments_created', models.PositiveIntegerField(default=0)),
                ('supplies_delivered', models.PositiveIntegerField(default=0)),
                ('compliance_submitted', models.PositiveIntegerField(default=0)),
                ('compliance_compliant', models.PositiveIntegerField(default=0)),
                ('compliance_unable', models.PositiveIntegerField(default=0)),
                ('milestones_due', models.PositiveIntegerField(default=0)),
                ('milestones_overdue', models.PositiveIntegerField(default=0)),
                ('milestones_completed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='accounts.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'day'], name='reporting_s_organiz_e536b0_idx')],
                'unique_together': {('organization', 'day')},
            },
        ),
    ]
