# Generated by Django 4.2.14 on 2025-11-13 16:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screening', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_phone_e164', models.CharField(db_index=True, max_length=20)),
                ('channel', models.CharField(default='whatsapp', max_length=16)),
                ('template_code', models.CharField(blank=True, max_length=64)),
                ('language', models.CharField(default='en', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], default='QUEUED', max_length=16)),
                ('provider_msg_id', models.CharField(blank=True, max_length=128)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.organization')),
                ('related_screening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='screening.screening')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'status'], name='messaging_m_organiz_c2b393_idx'), models.Index(fields=['scheduled_at', 'status'], name='messaging_m_schedul_da997e_idx')],
            },
        ),
    ]
