# Generated by Django 4.2.14 on 2025-11-18 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
        ('program', '0003_compliancesubmission'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='related_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='program.monthlysupply'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='related_screening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='screening.screening'),
        ),
    ]
