# Generated by Django 4.2.14 on 2025-11-21 21:16

from django.db import migrations, models
import uuid

def backfill_idempotency_keys(apps, schema_editor):
    MessageLog = apps.get_model('messaging', 'MessageLog')
    # Avoid pulling everything into memory if large:
    for row in MessageLog.objects.filter(idempotency_key__isnull=True).iterator():
        row.idempotency_key = uuid.uuid4().hex
        row.save(update_fields=['idempotency_key'])

class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_messagelog_related_supply_and_more'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='messagelog',
    #         name='idempotency_key',
    #         field=models.CharField(blank=True, db_index=True, max_length=160, unique=True),
    #     ),
    # ]

    operations = [
        # 1) add nullable, not unique, no default
        migrations.AddField(
            model_name='messagelog',
            name='idempotency_key',
            field=models.CharField(max_length=36, null=True, blank=True),
        ),
        # 2) backfill
        migrations.RunPython(backfill_idempotency_keys, migrations.RunPython.noop),
        # 3) make it unique (and non-null if you prefer)
        migrations.AlterField(
            model_name='messagelog',
            name='idempotency_key',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]