# Generated by Django 4.2.14 on 2025-11-22 03:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_messagelog_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='idempotency_key',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
    ]
