# Generated by Django 5.2.7 on 2026-02-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_organization_org_type_alter_orgmembership_role'),
        ('messaging', '0004_alter_messagelog_idempotency_key'),
        ('program', '0004_screeningmilestone'),
        ('screening', '0003_remove_screening_screening_s_student_3d255f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='pid',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='payload',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='to_phone_e164',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=20),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['organization', 'pid', 'created_at'], name='messaging_m_organiz_946cf6_idx'),
        ),
    ]
