# Generated by Django 4.2.14 on 2025-11-14 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roster', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('TEACHER', 'Teacher'), ('PARENT', 'Parent')], default='PARENT', max_length=16)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('FORWARDED', 'Forwarded to SAPA')], default='APPLIED', max_length=16)),
                ('form_lang', models.CharField(default='en', max_length=12)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('forwarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forwarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_applications', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='roster.guardian')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='roster.student')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'status'], name='assist_appl_organiz_acdb17_idx'), models.Index(fields=['student', 'status'], name='assist_appl_student_9ce91d_idx'), models.Index(fields=['created_at'], name='assist_appl_created_a6bd5c_idx')],
            },
        ),
    ]
