# Generated by Django 4.2.14 on 2025-11-15 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('assist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('ALL_PENDING', 'All pending'), ('TOP_N_ALPHA', 'Top-N alphabetic')], max_length=16)),
                ('n_selected', models.PositiveIntegerField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_batches', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_batches', to='accounts.organization')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='sapa_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('FORWARDED', 'Forwarded to SAPA'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='APPLIED', max_length=16),
        ),
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='assist.application')),
                ('approval_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assist.approvalbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['outcome', 'created_at'], name='assist_batc_outcome_b9f5f4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='approvalbatch',
            index=models.Index(fields=['organization', '-executed_at'], name='assist_appr_organiz_783c55_idx'),
        ),
    ]
