# Generated by Django 5.2.7 on 2026-02-07 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_organization_org_type_alter_orgmembership_role'),
        ('assist', '0003_application_income_verification_and_grants'),
        ('roster', '0001_initial'),
        ('screening', '0002_yellow_and_anthro_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='application',
            name='assist_appl_organiz_acdb17_idx',
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='assist_appl_student_9ce91d_idx',
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='assist_appl_created_a6bd5c_idx',
        ),
        migrations.AddField(
            model_name='application',
            name='pid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['organization', 'created_at'], name='assist_appl_organiz_6c206e_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='assist_appl_organiz_92a308_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['organization', 'pid', 'status', 'created_at'], name='assist_appl_organiz_ee4d9b_idx'),
        ),
    ]
