# Generated by Django 4.2.14 on 2026-01-19 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_organization_org_type_alter_orgmembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningSchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, default='', max_length=128)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('principal_name', models.CharField(blank=True, default='', max_length=255)),
                ('principal_email', models.EmailField(max_length=254)),
                ('operator_name', models.CharField(blank=True, default='', max_length=255)),
                ('operator_email', models.EmailField(blank=True, default='', max_length=254)),
                ('local_language_code', models.CharField(blank=True, default='', max_length=12)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening_only_profile', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningTermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(choices=[('ORG_ADMIN', 'School Admin'), ('TEACHER', 'Teacher')], max_length=16)),
                ('version', models.CharField(default='v1', max_length=32)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_only_terms_acceptances', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_only_terms_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organization', 'user', 'actor_role', 'version')},
            },
        ),
    ]
