# Generated by Django 4.2.14 on 2025-11-21 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
